name: 'My Custom Action'
description: 'Say Hello'
author: 'Arthur Wambst'

runs:
  uses: actions/checkout@v4

  uses: actions/setup-dotnet@v3
  with:
    dotnet-version: 8.x
  # You can test your matrix by printing the current dotnet version
  run: dotnet --version
  run: dotnet restore #./PartySmurf.sln
  run: dotnet build ./PartySmurf.sln --no-restore
  run: dotnet test ./XunitTESTS/XunitTESTS.csproj --no-build --verbosity normal --logger "html;logfilename=testResults.html"
