name: 'My Custom Action'
description: 'Say Hello'
author: 'Arthur Wambst'

inputs:
  token:
   description: “Username”
   required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - run: dotnet --version
      shell: bash
    - run: ls
      shell: bash
    - run: pwd
      shell: bash
    - run: curl -H 'Authorization: token $SUPER_SECRET' -H 'Accept: application/vnd.github.v3.raw' -O -L https://api.github.com/repos/owner/repo/contents/path #--user "$SUPER_SECRET"
      env:
        SUPER_SECRET: ${{ inputs.token }}
      shell: bash
    - run: ls
      shell: bash
    - run: dotnet restore #./PartySmurf.sln
      shell: bash   
    - run: dotnet build ./PartySmurf.sln --no-restore
      shell: bash
    - run: dotnet test ./XunitTESTS/XunitTESTS.csproj --no-build --verbosity normal --logger "html;logfilename=testResults.html"
      shell: bash
