name: 'My Custom Action'
description: 'Say Hello'
author: 'Arthur Wambst'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        dotnet-version: [ '8.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      # You can test your matrix by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore #./PartySmurf.sln
      - name: Build
        run: dotnet build ./PartySmurf.sln --no-restore
      - name: Test with the dotnet CLI
        run: dotnet test ./XunitTESTS/XunitTESTS.csproj --no-build --verbosity normal --logger "html;logfilename=testResults.html"

      - uses: LouisBrunner/checks-action@v1.6.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Code coverage
          conclusion: ${{ job.status }}
          output: '{"summary":"Code coverage"}'
          output_text_description_file: ./XunitTESTS/TestResults/testResults.html
