name: 'My Custom Action'
description: 'Say Hello'
author: 'Arthur Wambst'

inputs:
  site_username:
   description: “Username”
   required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - run: dotnet --version
      shell: bash
    - run: ls
      shell: bash
    - run: pwd
      shell: bash
    - run: curl https://drive.google.com/drive/folders/177WAQk9dW41d3GnRDRIPmcO34pcI_Q_p?usp=sharing --user "$SUPER_SECRET"
      env:
        SUPER_SECRET: ${{ inputs.site_username }}
      shell: bash
    - run: dotnet restore #./PartySmurf.sln
      shell: bash   
    - run: dotnet build ./PartySmurf.sln --no-restore
      shell: bash
    - run: dotnet test ./XunitTESTS/XunitTESTS.csproj --no-build --verbosity normal --logger "html;logfilename=testResults.html"
      shell: bash
