name: 'My Custom Action'
description: 'Say Hello'
author: 'Arthur Wambst'

inputs:
  token:
   description: “Username”
   required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - run: dotnet --version
      shell: bash
    - run: ls
      shell: bash
    - run: pwd
      shell: bash
    - run: "curl -H 'Authorization: token ${{ inputs.token }}' -H 'Accept: application/vnd.github.v3.raw' -o XunitTESTS.csproj -L https://api.github.com/repos/MiniMouliEPITALyon/TestxUnit/git/blobs/f7ae273be200e000b98169708064ce8517881eac"
      shell: bash
    - run: "curl -H 'Authorization: token ${{ inputs.token }}' -H 'Accept: application/vnd.github.v3.raw' -o Usings.cs -L https://api.github.com/repos/MiniMouliEPITALyon/TestxUnit/git/blobs/8c927eb747a6a304db265e6753aee6c47504f604"
      shell: bash
    - run: "curl -H 'Authorization: token ${{ inputs.token }}' -H 'Accept: application/vnd.github.v3.raw' -o UnitTest1.cs -L https://api.github.com/repos/MiniMouliEPITALyon/TestxUnit/git/blobs/077c0dfb909fb95d1ba8b8d76b1e0bf1fea60444"
      shell: bash
    - run: cat UnitTest1.cs
      shell: bash
    - run: cat Usings.cs
      shell: bash
    - run: cat XunitTESTS.csproj
      shell: bash
    - run: ls
      shell: bash
    - run: dotnet restore ./PartySmurf.sln
      shell: bash   
    - run: dotnet build ./PartySmurf.sln --no-restore
      shell: bash
    - run: dotnet test ./XunitTESTS.csproj --verbosity normal --logger "html;logfilename=testResults.html"
      shell: bash
