name: 'My Custom Action'
description: 'Say Hello'
author: 'Arthur Wambst'

inputs:
 registry_username:
   description: “Username for image registry”
   required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - run: dotnet --version
      shell: bash
    - run: ls
      shell: bash
    - run: pwd
      shell: bash
    - run: dotnet restore #./PartySmurf.sln
      shell: bash   
    - run: dotnet build ./PartySmurf.sln --no-restore
      shell: bash
    - run: dotnet test ./XunitTESTS/XunitTESTS.csproj --no-build --verbosity normal --logger "html;logfilename=testResults.html"
      shell: bash
